import { ClerkProvider } from "@clerk/nextjs"
import Header from "./components/Header"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import {Toaster} from "sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
           <Header/>
            <main className="min-h-screen">
              {children}
            </main>
            <Toaster richColors/>
            {/* footer */}
            <footer
            className="bg-foreground/10 py-12"
            >
              <div className="container mx-auto px-4 text-center font-bold text-gray-600">
              Made with ❤️ by Sejal and Arya
            </div>
            </footer>
        </body>
      </html>
    </ClerkProvider>
  )
}
